names:
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- z
- Berdoa
- Berjalan
- Bermain
- Berpikir
- Bicara
- Duduk
- Makan
- Mandi
- Melihat
- Membaca
- Membuat
- Memeluk
- Memukul
- Menangis
- Mendorong
- Menggambar
- Menuangkan
- Minum
- Saya
- Tidur
- berhenti
- Z
nc: 48
test: ../test/images
train: ../train/images
val: ../valid/images
